feat: capability to create runs on replay
goto/optimus pull request #62
Opened 2023-05-26 08:07 UTC by deryrahman

- [x] runs creation for non existing run within allowed date range
- [x] validation based on date range

2023-05-31 09:01 UTC, arinda-arif requested changes

2023-05-31 09:11 UTC, deryrahman commented on core/scheduler/service/replay_worker.go
> +		if err := w.replayRepo.UpdateReplay(ctx, replayReq.Replay.ID(), state, createdRuns, ""); err != nil {
runs which has created is on the running state, if the definition of replayed / partial-replayed is the running runs within the replay date range, then in this step, replay state should be replayed / partial-replayed. wdyt?

2023-05-31 09:20 UTC, arinda-arif commented on core/scheduler/service/replay_worker.go
> +		if err := w.replayRepo.UpdateReplay(ctx, replayReq.Replay.ID(), state, createdRuns, ""); err != nil {
agreed. in that case, the state is accurate and we can keep the update so if any issue when processing the existing runs, the created one's states are already updated. we can resolve this comment.

2023-06-05 04:04 UTC, arinda-arif commented on core/scheduler/service/replay_worker.go
> +	runsToBeCleared := scheduler.JobRunStatusList(replayReq.Runs).GetSortedRunsByStates([]scheduler.State{scheduler.StatePending})
@deryrahman now that you have updated `GetFirstExecutableRun`, I believe you can use it here.

2023-06-05 09:04 UTC, merged