feat: replay to support dry run
goto/optimus pull request #91
Opened 2023-06-28 08:51 UTC by deryrahman

2023-07-03 03:51 UTC, arinda-arif requested changes

2023-07-03 07:15 UTC, deryrahman commented on client/cmd/replay/create.go
> +func (r *createCommand) replayDryRun(replayReq *pb.ReplayRequest) error {
Have already verified that. Seems like the grpc is not strictly used that convention. It works by reusing the replay request paramenter

2023-07-04 05:21 UTC, deryrahman commented on client/cmd/replay/create.go
> +func (r *createCommand) replayDryRun(replayReq *pb.ReplayRequest) error {
As per our discussion, we will use dedicated replay parameter for dryrun

2023-07-05 08:02 UTC, arinda-arif commented on Makefile
> +PROTON_COMMIT := "b390e2b91f6cb645803317075ab2082fcfaabdd2"
let's do `make generate-proto`, as there will be some changes from other commits

2023-07-05 09:42 UTC, arinda-arif approved these changes

2023-08-01 08:14 UTC, merged